services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: always
    volumes:
      - ./searxng-config:/etc/searxng
      - ./searxng:/var/cache/searxng
    ports:
      - "8080:8080"

networks:
  searxng:
    name: searxng
