#!/usr/bin/env bash

awww-daemon &

# ---- CONFIG ----
IMG_SIZE=640
ROUNDNESS=30
CANVAS_W=1920
CANVAS_H=1080
DARKEN_FACTOR=0.75
BRIGHTNESS_THRESHOLD=0.23
# -----------------

while true; do
  playerctl --follow metadata mpris:artUrl -p spotify # resizing youtube thumbnails does *not* look good
  sleep 1
done | while IFS= read -r url; do
  curl -s "$url" -o /tmp/art

  magick /tmp/art -resize ${IMG_SIZE}x${IMG_SIZE}\> /tmp/art_${IMG_SIZE}.png

  mean=$(magick /tmp/art_${IMG_SIZE}.png -colorspace Gray -format "%[fx:mean]" info:)

  awk -v m="$mean" -v t="$BRIGHTNESS_THRESHOLD" 'BEGIN { exit !(m < t) }'
  if [ $? -eq 0 ]; then
    magick /tmp/art_${IMG_SIZE}.png -evaluate Multiply $DARKEN_FACTOR /tmp/art_${IMG_SIZE}.png
  fi

  magick /tmp/art_${IMG_SIZE}.png \
    \( -size ${IMG_SIZE}x${IMG_SIZE} xc:none -fill white \
       -draw "roundrectangle 0,0 ${IMG_SIZE},${IMG_SIZE} ${ROUNDNESS},${ROUNDNESS}" \) \
    -alpha set -compose copyopacity -composite \
    /tmp/art_masked.png

  magick -size ${CANVAS_W}x${CANVAS_H} xc:black \
    /tmp/art_masked.png -gravity center -composite \
    /tmp/wall.png

  awww img /tmp/wall.png --transition-type any
done
