services:
  unbound:
    container_name: unbound
    image: klutchell/unbound
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "Asia/Kolkata"
      FTLCONF_webserver_api_password: "correct horse battery staple"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "unbound"
    volumes:
      - "../../volumes/unbound-pihole/etc-pihole:/etc/pihole"
    restart: always
