# Stolen from https://www.youtube.com/watch?v=wuohFzr2QB4

background {
    path = /tmp/wall.png
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# INPUT FIELD
input-field {
    monitor =
    size = 120, 45
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(100, 114, 125, 0.4)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    font_family = SF Pro Text Semibold
    placeholder_text = Enter Password
    hide_input = false
    check_color = rgba(166, 227, 161, 0.8)
    fail_color = rgba(243, 139, 168, 0.8)
    position = 0, -420
    halign = center
    valign = center
    text_align = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +'%-I:%M:%S')</span>"
    color = rgba(216, 222, 233, 0.70)
    font_size = 130
    font_family = SF Pro Display Bold
    position = 0, 310 halign = center valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +'%A, %B %d')</span>"
    color = rgba(216, 222, 233, 0.70)
    font_size = 30
    font_family = SF Pro Display Semibold
    position = 0, 200
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = Karthikeyan KK
    color = rgba(216, 222, 233, 0.70)
    font_size = 28
    font_family = SF Pro Display Semibold
    position = 0, -350
    halign = center
    valign = center
}

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/hyprlock/current-song.sh)"
    color = rgba(255, 255, 255, 0.7)
    font_size = 36
    font_family = SF Pro Display
    position = 0, -20
    halign = center
    valign = center
    text_align = center
}

# MEDIA CONTROLS - BACKGROUNDS
shape {
    monitor =
    size = 80, 80
    rounding = -1
    color = rgba(243, 139, 168, 0.15)
    position = -140, -150
    halign = center
    valign = center
}

shape {
    monitor =
    size = 80, 80
    rounding = -1
    color = rgba(243, 139, 168, 0.15)
    position = 0, -150
    halign = center
    valign = center
}

shape {
    monitor =
    size = 80, 80
    rounding = -1
    color = rgba(243, 139, 168, 0.15)
    position = 140, -150
    halign = center
    valign = center
}

# MEDIA CONTROLS - ICONS
label {
    monitor =
    text = 
    font_family = GeistMono Nerd Font Propo
    font_size = 30
    color = rgba(243, 139, 168, 0.9)
    position = -140, -150
    halign = center
    valign = center
    onclick = playerctl previous
}

label {
    monitor =
    text = 
    font_family = GeistMono Nerd Font Propo
    font_size = 30
    color = rgba(243, 139, 168, 0.9)
    position = 0, -150
    halign = center
    valign = center
    onclick = playerctl play-pause
}

label {
    monitor =
    text = 
    font_family = GeistMono Nerd Font Propo
    font_size = 30
    color = rgba(243, 139, 168, 0.9)
    position = 140, -150
    halign = center
    valign = center
    onclick = playerctl next
}
