{{- if eq .chezmoi.os "windows" }}
["AppData/Roaming/bat/themes/Catppuccin Mocha.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "168h"

[".local/bin/mousemaster.exe"]
type = "file"
url = '{{ gitHubLatestReleaseAssetURL "petoncle/mousemaster" "mousemaster.exe" }}'
refreshPeriod = "48h"

["catppuccin.omp.json"]
type = "file"
url = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/catppuccin_mocha.omp.json"
refreshPeriod = "168h"

["AppData/Roaming/spicetify/Extensions/adblock.js"]
type = "file"
url = "https://raw.githubusercontent.com/rxri/spicetify-extensions/refs/heads/main/adblock/adblock.js"
refreshPeriod = "2h"

["AppData/Roaming/spicetify/Extensions/spicy-lyrics.mjs"]
type = "file"
url = "https://raw.githubusercontent.com/Spikerko/spicy-lyrics/refs/heads/main/builds/spicy-lyrics.mjs"
refreshPeriod = "2h"
{{- end }}

[".config/eza/theme.yml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/eza/refs/heads/main/themes/mocha/catppuccin-mocha-pink.yml"
refreshPeriod = "168h"


[".config/catppuccin.gitconfig"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/delta/refs/heads/main/catppuccin.gitconfig"
refreshPeriod = "168h"
