formatters = ["nixfmt"]

[global]
excludes = [
  ".git",
  "result",
  "secrets",
]

[formatter.nixfmt]
command = "nixfmt"
includes = [
  "flake.nix",
  "options/**/*.nix",
  "hosts/**/*.nix",
  "modules/**/*.nix",
]
