#!/usr/bin/env bash

set -euo pipefail

# sudo nix flake update
sudo nix fmt # needs sudo or breaks bcz of random permission stuff
git add --all
git diff --cached
sudo nixos-rebuild switch
git commit -m "$*"
git push
