services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    container_name: watchtower
    command: --interval 3600
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
