services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ../../volumes/portainer/portainer_data:/data
