[tools]
node = "latest"
rust = "latest"
bun = "latest"
go = "latest"
uv = "latest"
"cargo:sccache" = "latest"
cargo-binstall = "latest"

"github:fastfetch-cli/fastfetch" = "latest"
"github:sharkdp/hyperfine" = "latest"
"github:jesseduffield/lazydocker" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:zricethezav/gitleaks" = "latest"
"github:FiloSottile/age" = "latest"
"github:dandavison/delta" = "latest"
"github:sharkdp/fd" = "latest"
"github:junegunn/fzf" = "latest"
"github:ajeetdsouza/zoxide" = "latest"
"github:eza-community/eza" = "latest"
"github:sharkdp/bat" = "latest"
"github:charmbracelet/glow" = "latest"
"github:jgm/pandoc" = "latest"
"github:cli/cli" = "latest"
"github:BurntSushi/ripgrep" = "latest"
jq = "latest"

"pipx:yt-dlp" = "latest"
"pipx:spotdl" = "latest"
"pipx:ocrmypdf" = { version = "latest", uvx_args = "--with ocrmypdf-easyocr --python 3.12" }
"pipx:copyparty" = "latest"
"pipx:mcpo" = "latest"
"pipx:tldr" = "latest"
"pipx:xonsh" = "latest"
"pipx:pycowsay" = "latest"
"pipx:magic-wormhole" = "latest"

"npm:opencode-ai" = "latest"
"npm:vercel" = "latest"

"cargo:gitoxide" = "latest"

"go:github.com/samyakbardiya/trex" = "latest"
"go:github.com/TheZoraiz/ascii-image-converter" = "latest"

[settings]
pipx.uvx = true
npm.package_manager = "bun"
cargo.binstall = true
