[tools]
node = "latest"
rust = "latest"
bun = "latest"
go = "latest"
uv = "latest"
"cargo:sccache" = "latest"
cargo-binstall = "latest"

"ubi:fastfetch-cli/fastfetch" = "latest"
"ubi:sharkdp/hyperfine" = "latest"
"ubi:jesseduffield/lazydocker" = "latest"
"ubi:jesseduffield/lazygit" = "latest"
"ubi:zricethezav/gitleaks" = "latest"
"ubi:FiloSottile/age" = "latest"
"ubi:dandavison/delta" = "latest"
"ubi:sharkdp/fd" = "latest"
"ubi:junegunn/fzf" = "latest"
"ubi:ajeetdsouza/zoxide" = "latest"
"ubi:eza-community/eza" = "latest"
"ubi:sharkdp/bat" = "latest"
"ubi:charmbracelet/glow" = "latest"
"ubi:jgm/pandoc" = "latest"
"ubi:cli/cli" = { version = "latest", exe = "gh" }
"ubi:BurntSushi/ripgrep" = { version = "latest", exe = "rg" }
jq = "latest"

"pipx:yt-dlp" = "latest"
"pipx:spotdl" = "latest"
"pipx:ocrmypdf" = { version = "latest", uvx_args = "--with ocrmypdf-easyocr --python 3.12" }
"pipx:copyparty" = "latest"
"pipx:mcpo" = "latest"
"pipx:tldr" = "latest"
"pipx:xonsh" = "latest"
"pipx:pycowsay" = "latest"

"npm:opencode-ai" = "latest"
"npm:vercel" = "latest"

"cargo:gitoxide" = "latest"

"go:github.com/samyakbardiya/trex" = "latest"
"go:github.com/TheZoraiz/ascii-image-converter" = "latest"

[settings]
pipx.uvx = true
npm.package_manager = "bun"
cargo.binstall = true
