services:
  libremdb:
    container_name: libremdb
    image: ghcr.io/zyachel/libremdb:main
    ports:
      - "3007:3000"
    env_file: .env.local.example
    depends_on:
      - libremdb-redis
    restart: always
    user: 65534:65534
    read_only: true
    tmpfs:
      - /opt/app/.next/cache/:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  libremdb-redis:
    container_name: libremdb_redis
    image: redis
    restart: always
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL
