services:
  rimgo:
    container_name: rimgo
    image: quay.io/pussthecatorg/rimgo
    ports:
      - 3008:3000
    restart: always
    user: 65534:65534
    read_only: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    env_file: .env
