services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3001:8080"
    volumes:
      - ../../volumes/open-webui/openwebui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
