[deployment]
    host = "0.0.0.0"
    port = 8000
#    domain = priviblur.example.com
    https = false
    workers = 1

[cache]
    url = "redis://priviblur-redis:6379"

    cache_active_poll_results_for = 3600
    cache_expired_poll_results_for = 86400
    cache_feed_for = 3600
    cache_blog_feed_for = 3600
    cache_blog_post_for = 300

[priviblur_backend]
    main_response_timeout = 10
    image_response_timeout = 30

[default_user_preferences]
     theme = "dark"
     language = "en_US"

[logging]
    sanic_logging_level = 30
    priviblur_logging_level = 30
    priviblur_extractor_logging_level = 20


[misc]
    dev_mode = false
