services:
  priviblur:
    image: quay.io/syeopite/priviblur:latest
    container_name: priviblur
    restart: always
    ports:
      - "3011:8000"
    volumes:
      - ./config.toml:/priviblur/config.toml:Z,ro

  priviblur-redis:
    image: redis:6.2-alpine
    container_name: priviblur-redis
    command: redis-server --loglevel warning
    volumes:
      - ../../volumes/priviblur/priviblur-redis:/data
    restart: always
    user: "999:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
